language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t mikefeldberg/cookbook -f ./frontend/Dockerfile.dev ./frontend

script:
  - docker run -e CI=true mikefeldberg/cookbook npm test

after_success:
  - docker build -t mikefeldberg/cookbook-frontend ./frontend
  - docker build -t mikefeldberg/cookbook-nginx ./nginx
  - docker build -t mikefeldberg/cookbook-backend ./backend

  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

  - docker push mikefeldberg/cookbook-frontend
  - docker push mikefeldberg/cookbook-nginx
  - docker push mikefeldberg/cookbook-backend

deploy:
  - provider: elasticbeanstalk
    region: 'us-west-1'
    app: $AWS_DEV_APP
    env: $AWS_DEV_ENV
    bucket_name: $AWS_BUCKET_PATH
    bucket_path: $AWS_DEV_APP
    on:
      branch: develop
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY

  - provider: elasticbeanstalk
    region: 'us-west-1'
    app: $AWS_PROD_APP
    env: $AWS_PROD_ENV
    bucket_name: $AWS_BUCKET_PATH
    bucket_path: $AWS_PROD_APP
    on:
      branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
