version: '3'
services:
    nginx:
        restart: always
        build:
            dockerfile: Dockerfile.dev
            context: ./nginx
        depends_on:
            - api
            - frontend
        ports:
            - '3050:80'
    api:
        depends_on:
            - postgres
        build:
            dockerfile: ./Dockerfile.dev
            context: ./backend
        environment:
            - PGHOST=postgres
            - PGPORT=5432
            - PGDATABASE=cookbook
            - PGUSER=postgres
            - PGPASSWORD=postgres_password
        ports:
            - '8000:8000'
        volumes:
            - ./backend:/usr/src/app
        command: manage.py runserver 0.0.0.0:8000
    frontend:
        build:
            dockerfile: ./Dockerfile.dev
            context: ./frontend
        volumes:
            - /app/node_modules
            - ./frontend:/app
        stdin_open: true
    postgres:
        image: postgres:latest
        environment:
            - POSTGRES_DB=cookbook
            - POSTGRES_PASSWORD=postgres_password
        volumes:
            - ./postgres-data:/var/lib/postgresql/data
        ports:
            - "5432:5432"
