version: '3'
services:
    nginx:
        restart: always
        depends_on:
            - api
            - frontend
        build:
            dockerfile: Dockerfile
            context: ./nginx
        ports:
            - '3050:80'
    api:
        restart: on-failure
        build:
            dockerfile: ./Dockerfile
            context: ./backend
        volumes:
            - ./backend:/usr/src/app
        # env_file:
        #     - ./backend/.env
        environment:
            - PGHOST=postgres
            - PGPORT=5432
            - PGDATABASE=cookbook
            - PGUSER=postgres
            - PGPASSWORD=postgres_password
    frontend:
        build:
            dockerfile: ./Dockerfile
            context: ./frontend
        volumes:
            - /app/node_modules
            - ./frontend:/app
        stdin_open: true
    postgres:
        image: postgres:latest
        environment:
            - POSTGRES_DB=cookbook
            - POSTGRES_PASSWORD=postgres_password
        volumes:
            - ./postgres-data:/var/lib/postgresql/data
        ports:
            - "5432:5432"