# FROM python:3
# ENV PYTHONUNBUFFERED 1

# WORKDIR /usr/app/

# COPY . .
# RUN pip install pipenv
# RUN pipenv install --system --deploy --ignore-pipfile

FROM python:3

WORKDIR /usr/src/app

ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

RUN pip install --upgrade pip
COPY ./requirements.txt /usr/src/app/requirements.txt
RUN pip install -r requirements.txt

# copy project
COPY . /usr/src/app/
