FROM python:3.7-slim-buster
WORKDIR /usr/src/app

ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

RUN pip install --upgrade pip
COPY Pipfile Pipfile.lock /usr/src/app/
RUN pip install pipenv && pipenv install --system
COPY . /usr/src/app/

# ENTRYPOINT ["sh", "/usr/src/app/entrypoint.dev.sh"]
# ENTRYPOINT ["/usr/src/app/entrypoint.dev.sh"]

ENTRYPOINT ["python"]
CMD ["manage.py", "test", "--settings=backend.settings.testing", "--keepdb"]

