recipes = [
    {
        'title': 'Instant Pot Plov (Rice Pilaf)',
        'photo': 'https://feldbergscookbook-photos.s3-us-west-1.amazonaws.com/photo_01E6C5YFY69DNP6Q1GG6SH9XJ5.jpeg',
        'description': 'Plov is a hearty dish that comes in many varieties. Just about every Eastern European or Central Asian culture has a version. This one comes pretty close to what my grandma used to make so I’m gonna surmise that it’s got Russian roots. While my grandma’s plov took many painstaking hours to prepare, this pressure cooker approach gets us there with minimal effort and in less than half the time.',
        'ingredients': [
            {'quantity': '2 1/2 cups', 'name': 'your favorite rice (I usually go with basmati or jasmine, but it works with short-grain as well.)', 'preparation': 'rinsed and drained'},
            {'quantity': '1 lb', 'name': 'beef chuck or beef stew meat', 'preparation': 'cut into 3/4″ pieces'},
            {'quantity': '4 tbsp', 'name': 'olive oil'},
            {'quantity': '4 tbsp', 'name': 'butter'},
            {'quantity': '1', 'name': 'large onion', 'preparation': 'diced'},
            {'quantity': '3', 'name': 'large carrots',
                'preparation': 'grated'},
            {'quantity': '3 cups', 'name': 'very warm water'},
            {'quantity': '1 tbsp', 'name': 'salt'},
            {'quantity': '1/2 tsp', 'name': 'black pepper'},
            {'quantity': '1/2 tsp', 'name': 'ground cumin'},
            {'quantity': '1/2 tsp', 'name': 'ground paprika'},
            {'quantity': '1/2 tsp', 'name': 'ground coriander'},
            {'quantity': '1', 'name': 'whole head garlic',
                'preparation': 'unpeeled, cut in half crosswise'},
            {'quantity': '1 tbsp', 'name': 'freshly chopped parsley to garnish – optional'},
        ],
        'instructions': [
            'Rinse and drain rice and set aside. Set Instant Pot to sauté and add 4 tbsp olive oil.',
            'Once oil is hot (but not smoking), add beef in a single layer and sauté until lightly browned (usually 5 min but may take longer if your cooking surface is crowded), stirring occasionally.',
            'Add 4 tbsp butter and chopped onion and stir 3 minutes until softened.',
            'Add grated carrots along with seasoning mix (1 tbsp salt, 1/2 tsp pepper, 1/2 tsp cumin, 1/2 tsp paprika, 1/2 tsp coriander) and sauté 5 minutes until softened, stirring occasionally.',
            'Spread rice evenly over the top (do not stir). Push garlic halves, cut-side-down, halfway into the rice. Pour very warm (or hot) water directly over the garlic cloves so you don’t disturb the rice. Use the back of a wooden spoon to poke 5-7 holes through the rice to the bottom of the pot.',
            'Cover and cook for 30 minutes on high pressure.',
            'Give the Instant Pot 10 minutes to depressurize before opening the steam release valve. Open pot once it’s fully depressurized',
            'Remove garlic and set aside. Stir contents to combine all ingredients.',
            '(Optional) If you love garlic, squeeze the garlic cloves back into the pot (they should easily slide out of the peel) and stir again.'
        ],
        'skill_level': 'Easy',
        'prep_time': 20,
        'wait_time': 0,
        'cook_time': 30,
        'total_time': 50,
        'servings': 8,
    },
    {
        'title': 'Borsh',
        'photo': 'https://feldbergscookbook-photos.s3-us-west-1.amazonaws.com/photo_01E6C6ATD2QN2BT3TGDSNJY2MX.JPG',
        'description': 'Classic Ukranian beet soup. Can be made as hearty or light as you like. I tend to opt for a heartier/denser version and I use a 12qt stockpot for this recipe. So, if you like your soup more soupy, feel free to reduce the vegetable quantities by 20-30% of what’s listed below',
        'ingredients': [
            {'quantity': '2 lb', 'name': 'Beef chuck/stew meat',
                'preparation': 'cut into 1 inch cubes'},
            {'quantity': '1', 'name': 'Beef marrow bone (optional)'},
            {'quantity': '2 tbsp', 'name': 'salt (+ more to taste)'},
            {'quantity': '3 large or 6 medium', 'name': 'beets',
                'preparation': 'washed, peeled, and grated'},
            {'quantity': '4 tbsp', 'name': 'olive oil'},
            {'quantity': '2',
                'name': 'large onions (white or yellow)', 'preparation': 'chopped'},
            {'quantity': '5 medium', 'name': 'carrots', 'preparation': 'grated'},
            {'quantity': '2 large or 4 medium', 'name': 'potatoes',
                'preparation': 'peeled and cut into 1 inch cubes'},
            {'quantity': '1 head', 'name': 'green cabbage',
                'preparation': 'julienned'},
            {'quantity': '2', 'name': 'tomatoes',
                'preparation': 'roughly chopped'},
            {'quantity': '3', 'name': 'bay leaves'},
            {'quantity': '1/2 tsp', 'name': 'freshly ground black pepper'},
            {'quantity': '1/3 cup', 'name': 'fresh parsley', 'preparation': 'chopped'},
            {'quantity': '3 cloves', 'name': 'garlic', 'preparation': 'pressed or minced'},
        ],
        'instructions': [
            'Cut beef into 1" cubes and place in a large stockpot (add marrow bone if using one). Fill halfway with cold water. Add bayleaves and 2 tbsp salt and set over a high flame. (Note: If at any point it looks like you have too much water, just let some boil off before adding extra ingredients. I also keep a kettle of boiled water on the side just in case it looks like I don’t have enough.)',
            'As the water comes to boil, periodically remove the foam crud as soon as it surfaces. This is purely for aesthetics. The brownish foam is broken down proteins; it’s not bad for you, but it makes for a cloudy soup.',
            'Once the water is boiling, reduce heat, partially cover, and simmer for 45 minutes to an hour.',
            'Grate beets on the large grater holes (or use a food processor. I bought mine a few winters ago after making borsh three weeks in a row and not being able to look at my grater anymore). Place grated beets in a large saute pan or heavy-bottom skillet with 4 tbsp olive oil and 1 tbsp vinegar and saute for 5-10 minutes on medium heat. Then, reduce heat to medium/low and add chopped tomatoes. Mix thoroughly and saute until contents start to soften, stir as needed (about every 10-15 min). Remove from pan and set aside.',
            'In the same skillet (no need to wash it), saute chopped onion in 1 tbsp butter for 5 minutes. Add grated carrot and sautee another 5 min or until softened, adding more oil and/or lower heat if contents seem like they are starting to burn.',
            'While the onions/carrots are cooking, julienne the cabbage and cube the potatoes.'
            'Once the meat has been cooking at least 45 min, add julienned cabbage to the stock',
            'Once the cabbage has softened (about 10 minutes), add cubed potatoes, onions, and carrots.',
            'Wait 10 minutes, then add the beets.',
            'After 10 minutes of simmering everything together, remove the pot from heat, add chopped parsley and pressed garlic, stir and cover. Let rest for 20 minutes for the flavors to diffuse.',
            'Serve with a dollop of sour cream (technically optional but absolutely essential in my home)',
        ],
        'skill_level': 'Medium',
        'prep_time': 30,
        'wait_time': 0,
        'cook_time': 90,
        'total_time': 120,
        'servings': 8,
    },
    {
        'title': 'Goulash Stew',
        'photo': 'https://feldbergscookbook-photos.s3-us-west-1.amazonaws.com/photo_01E6C6M74CQJGY14KQ4TP8E0HC.jpg',
        'description': 'Some of the best goulash I’ve ever had was at Cafe Katja, a little Austrian place on Orchard Street in New York. Traditional Hungarian Goulash is a light beef soup. Cafe Katja made theirs into a thick, melt-in-your-mouth stew. This recipe comes pretty close to Cafe Katja’s goulash.',
        'ingredients': [
            {'quantity': '4 tbsp', 'name': 'olive oil'},
            {'quantity': '2 1/2 lbs', 'name': 'lean stewing beef',
                'preparation': 'cut into 1 inch pieces'},
            {'quantity': '1 tsp', 'name': 'salt or to taste'},
            {'quantity': '1 tsp', 'name': 'pepper or to taste'},
            {'quantity': '2', 'name': 'large onions',
                'preparation': 'roughly chopped'},
            {'quantity': '5 cloves', 'name': 'garlic', 'preparation': 'minced'},
            {'quantity': '3 tbsp', 'name': 'sweet paprika'},
            {'quantity': '1 tsp', 'name': 'caraway seeds', 'preparation': 'ground'},
            {'quantity': '1 tsp', 'name': 'dried oregano'},
            {'quantity': '3', 'name': 'bay leaves'},
            {'quantity': '1 tsp', 'name': 'brown sugar'},
            {'quantity': '1/2 cup', 'name': 'tomato sauce OR 2 tomatoes'},
            {'quantity': '2 tbsp', 'name': 'balsamic vinegar'},
            {'quantity': '4 cups', 'name': 'beef broth (I use half a bullion cube and water)'},
            {'quantity': '2 tbsp', 'name': 'parsley',
                'preparation': 'chopped, for garnish'},
        ],
        'instructions': [
            'Heat a large deep skillet or Dutch oven over medium-high heat then add olive oil (You can also use an an Instant Pot).',
            'When the oil is hot, add beef. Season generously with salt and pepper and sear the beef until it starts to brown (usually 5 min but may take longer if you have a crowded cooking surface).',
            'Add onions and garlic and cook until the onions soften and become translucent (5-10 minutes). Reduce heat to medium.',
            'Add paprika, caraway seeds, oregano, bay leaves and brown sugar. Stir everything together and cook for 30 seconds.',
            'Add the tomato sauce (or tomatoes), balsamic vinegar, beef broth (or bullion) and stir (if using Instant Pot, add only 2 cups of broth).',
            'Bring to a boil, then cover and cook on low heat for about 2 hours or until the beef is fork-tender, stirring occasionally. The liquid will reduce down a lot as the beef cooks, so add more water as needed to maintain a stew consistency.',
            'If using Instant Pot, once the pot comes to boil, cover and seal pot. Cook on high pressure for 35 minutes. Once done, let the pot depressurize on its own for 15-20 minutes before releasing pressure.',
            '(Optional) At this point, you’ll have some soupy goulash. From here, I like to return it to heat and simmer down until it’s reduced to desired thickness.'
            'Taste for seasoning and adjust with salt and pepper as needed.',
            'Garnish with chopped parsley and serve over noodles or mashed potatoes.',
        ],
        'skill_level': 'Medium',
        'prep_time': 10,
        'wait_time': 0,
        'cook_time': 180,
        'total_time': 190,
        'servings': 8,
    },
    {
        'title': 'Linguine with White Clam Sauce',
        'photo': 'https://feldbergscookbook-photos.s3-us-west-1.amazonaws.com/photo_01E6C6517H10JCCA35H388PX5R.jpg',
        'description': 'There are a lot of ways to prepare linguine with clam sauce, but I’ve repeatedly gone back to this one because it’s one of the simpler approaches and yields delicious results. This recipe uses canned instead of fresh clams, which means all of the necessary ingredients can hang out in your kitchen cabinet for months.',
        'ingredients': [
            {'quantity': '1 pound', 'name': 'linguini'},
            {'quantity': '1 tsp', 'name': 'salt'},
            {'quantity': '1/4 cup', 'name': 'extra-virgin olive oil'},
            {'quantity': '8 fillets', 'name': 'flat anchovies'},
            {'quantity': '4 cloves', 'name': 'garlic', 'preparation': 'chopped'},
            {'quantity': '1 teaspoon', 'name': 'dried thyme leaves'},
            {'quantity': '1/2 tsp', 'name': 'crushed red pepper flakes'},
            {'quantity': '1/2 cup', 'name': 'dry white wine'},
            {'quantity': '2 (15 oz) cans',
             'name': 'whole or chopped baby clams with their juice (minced will do in a pinch; you’ll still get all the flavor but the clam texture will be lost)'},
            {'quantity': '1 handful', 'name': 'flat-leaf parsley',
                'preparation': 'chopped'},
        ],
        'instructions': [
            'Bring a large pot of water to boil. Use just enough water to ensure your pasta will be fully submerged for the 11-14 minutes it will take to cook. ',
            'Add salt and linguini and cook to an extra chewy al dente. The linguini will cook more in sauce. (I know the ingredients say 1 tsp salt, but I always cook pasta the same way: salt the water until it tastes like the sea.)',
            'While the pasta is cooking, prepare the sauce: place a large skillet or sautee pan over medium heat and add oil, anchovies, garlic, thyme, and red pepper flakes.',
            'Cook together until anchovies melt into oil and disintegrate completely. Be careful not to burn the garlic; stir frequently and reduce heat if needed.',
            'Add wine, clams, and clam juice to the pan, turn heat to high, and give the pan a shake: jostle back and forth for about 3-5 minutes (you should see a mist evaporating off the sauce). Don’t leave pan unattended or still for this part as the garlic will burn if left sitting on high heat (learned that the hard way by ruining a batch of sauce at the very end). Reduce to a low simmer.',
            '(Optional) You can add a separate bottle of clam juice to give more briney flavor to your sauce.',
            'When pasta is ready, use tongs to transfer directly from the pot into the sauce. The starchy water will help the sauce coat the pasta.',
            'Toss the pasta in sauce until well mixed, cover, and let sit for 5 minutes to allow the flavor to absorb.',
            'Remove from heat, add parsley, and serve.',
        ],
        'skill_level': 'Easy',
        'prep_time': 10,
        'wait_time': 0,
        'cook_time': 25,
        'total_time': 35,
        'servings': 4,
    },
    {
        'title': 'Blueberry Buttermilk Pancakes',
        'photo': 'https://feldbergscookbook-photos.s3-us-west-1.amazonaws.com/photo_01E6C6EA4WHQ4WT5P8XT4Z31HE.JPG',
        'description': 'The perfect lazy Sunday breakfast. These are also fantastic with other fruit or left plain.',
        'ingredients': [
            {'quantity': '2 cups', 'name': 'all-purpose flour'},
            {'quantity': '1/4 cup', 'name': 'sugar'},
            {'quantity': '2 1/4 teaspoons', 'name': 'baking powder'},
            {'quantity': '1/2 teaspoon', 'name': 'baking soda'},
            {'quantity': '1/2 teaspoon', 'name': 'salt'},
            {'quantity': '4', 'name': 'eggs'},
            {'quantity': '2 cups', 'name': 'buttermilk'},
            {'quantity': '2 tbsp', 'name': 'unsalted butter, plus more for frying'},
            {'quantity': '1 cup', 'name': 'blueberries', 'preparation': 'fresh or frozen'},
            {'quantity': '', 'name': 'maple syrup', 'preparation': 'to taste'},
            {'quantity': '', 'name': 'sour cream', 'preparation': 'to taste'},
        ],
        'instructions': [
            'I like to set up for this by laying out three mixing bowls to work in. One of them should be large enough to hold all the ingredients (not including any fruits or berries you’re using). Three nested bowls are pretty perfect for this.',
            'Prepare your dry mix in the large bowl: Sift together the flour, baking powder, baking soda, and salt (NO sugar here yet). (Note: You can do this in advance and stick it in the freezer. When using mix from the freezer, resift the contents before combining with wet ingredients.)',
            'Separate egg whites and yolks between the other two bowls: whites in the larger bowl, yolks in the smaller.',
            'Melt 2 tbsp (1/4 cup) butter and set aside. Use low heat so your butter doesn’t burn.',
            'Add sugar to egg yolks and whisk together (immersion blender also works for this and the next step).',
            'Whisk the egg whites until they’re foamy, then combine with buttermilk.',
            'Once your butter has cooled down, slowly pour it into the egg yolk/sugar mixture while whisking. Pouring hot butter onto the yolks will cook them so make sure you give it enough time to cool off.',
            'Pour the yolk/sugar/butter mixture into the whites/buttermilk mixture and whisk together.',
            'Once the wet mix is ready, pour it over the dry mix and stir to create a lumpy batter. Be careful not to over mix, or you’ll get less than fluffy pancakes. For reference: your mix should not be smooth and uniform; you should still see clumps of flour in it.',
            'Heat some butter in a skillet over low-medium heat (any skillet will do, but nonstick will save you a headache here). Use a large soup spoon to scoop a heaping spoonful of batter onto the skillet. Sprinkle the top with some of the blueberries. Cook for 2 to 3 minutes on each side. You’ll probably need 1-2 test rounds to calibrate the right temperature and cooking time combinations.',
            'Serve with a dollop of sour cream and maple syrup.',
        ],
        'skill_level': 'Easy',
        'prep_time': 15,
        'wait_time': 0,
        'cook_time': 25,
        'total_time': 40,
        'servings': 4,
    },
    {
        'title': 'Pan Roasted Chicken Thighs',
        'photo': 'https://feldbergscookbook-photos.s3-us-west-1.amazonaws.com/photo_01E6DHN6F13XTAN845HC03322S.jpg',
        'description': 'This chicken recipe super simple and game-changing. At least if your game, like mine, has ever involved making dry, rubbery, simultaneously over and under cooked chicken. This recipe is from The Bon Appétit Test Kitchen and produces perfectly crispy, juicy, flavorful fried chicken every single time.',
        'ingredients': [
            {'quantity': '4-8', 'name': 'Skin-on, bone-in chicken thighs'},
            {'quantity': '', 'name': 'Kosher salt'},
            {'quantity': '', 'name': 'Freshly ground black pepper'},
            {'quantity': '1 tbsp', 'name': 'vegetable oil'},
        ],
        'instructions': [
            'Preheat oven to 475°F.',
            'Season chicken generously with salt and pepper.',
            'Heat oil in a 12" cast-iron or heavy non-stick skillet over high heat until hot but not smoking.',
            'Nestle chicken in skillet, skin side down, and cook 2 minutes',
            'Reduce heat to medium-high; continue cooking skin side down, occasionally rearranging chicken thighs and rotating pan to evenly distribute heat, until fat renders and skin is golden brown, about 12 minutes',
            'Transfer skillet to oven and cook 13 more minutes.',
            'Flip chicken; continue cooking until skin crisps and meat is cooked through, about 5 minutes longer.',
            'Transfer to a plate; let rest 5 minutes before serving.',
        ],
        'skill_level': 'Easy',
        'prep_time': 5,
        'wait_time': 0,
        'cook_time': 30,
        'total_time': 35,
        'servings': 4,
    },
    {
        'title': 'Vegan Wild Rice Salad',
        'photo': 'https://feldbergscookbook-photos.s3-us-west-1.amazonaws.com/photo_01E6C8F50GP7FX6CMYFYPST74Q.jpg',
        'description': 'A fool-proof, healthy, crowd-pleaser to bring to a summer bbq.',
        'ingredients': [
            {'quantity': '1 cup', 'name': 'wild rice'},
            {'quantity': '1 (6-ounce) jar', 'name': 'marinated artichoke hearts',
             'preparation': 'drained and halved, reserve marinade'},
            {'quantity': '1 14oz can', 'name': 'green peas', 'preparation': 'drained'},
            {'quantity': '1/2 ', 'name': 'green bell pepper',
                'preparation': 'diced'},
            {'quantity': '3 stalks', 'name': 'scallion/green onions',
                'preparation': 'chopped, white and green parts'},
            {'quantity': '1 cup', 'name': 'cherry or grape tomatoes',
                'preparation': 'halved'},
            {'quantity': '1 tsp', 'name': 'salt'},
            {'quantity': '1/4 cup', 'name': 'extra virgin olive oil'},
            {'quantity': '1/4 tsp', 'name': 'paprika'},
            {'quantity': '1/4 tsp', 'name': 'ground cumin'},
        ],
        'instructions': [
            'Bring 2 cups water and 1/2 tsp salt to a boil. Add the rice and stir. Reduce heat to low, cover, and let simmer until soft (45 minutes to 1 hour). Drain excess liquid from the rice and leave out to cool. Rice holds heat pretty well so if you mix in the remaining ingredients while your rice is hot, it may be too hot to eat right away and can mushify all the fresh veggies while you wait.',
            'Meanwhile, combine EVOO, artichoke marinade, paprika, cumin, and remaining salt in a jar with a tight-fitting lid and shake well. Refrigerate until ready to use.',
            'In a large bowl, combine the rice, artichoke hearts, peas, green pepper, green onions, tomatoes, and half of the dressing. Toss well. Cover and chill or eat at room temperature. Just before serving, toss again and taste.'
        ],
        'skill_level': 'Easy',
        'prep_time': 15,
        'wait_time': 0,
        'cook_time': 45,
        'total_time': 60,
        'servings': 8,
    },
    {
        'title': 'Tim’s Grandma’s Crepes',
        'photo': 'https://feldbergscookbook-photos.s3-us-west-1.amazonaws.com/photo_01E6C6JEN63JWSH12ZR3AVVWRM.jpg',
        'description': 'This is a dangerous recipe. Dangerous because of how quickly you can get from raw materials to perfect crepes. Once you’ve prepped the batter, it won’t be long before you’re making reliably perfect crepes. You must first, of course, make one too thick, one too thin, one too raw, one that’s entirely on fire, and a few that fall apart mid-flip. Crepes can be finicky, so I highly recommend using a nonstick crepe-pan and a thin fish spatula.',
        'ingredients': [
            {'quantity': '1.5 cups', 'name': 'flour'},
            {'quantity': '3 cups', 'name': 'whole milk'},
            {'quantity': '3', 'name': 'eggs'},
            {'quantity': '4 tbsp', 'name': 'sugar'},
            {'quantity': '3/4 tsp', 'name': 'apple cider vinegar'},
            {'quantity': '1 tbsp', 'name': 'butter', 'preparation': 'melted'},
            {'quantity': '1 tsp', 'name': 'salt'},
        ],
        'instructions': [
            'Combine all ingredients and mix thoroughly with a whisk or immersion blender.',
            'Warm pan over medium-low heat.',
            '(optional) add a thin coat of oil or butter to the pan.',
            'Lift the pan off the heat. Pour about half a ladle of batter onto the pan and tilt it in a circular motion so that the batter coats the entire surface of the pan. Once the batter stops being runny, place the pan back down. If your crepe has a hole or two, drip in a little more batter to fill. You’ll have a better idea of how much batter you should be ladling after the first few crepes.',
            'Once the batter has mostly cooked through and can be turned without breaking, use a spatula to carefully peel the crepe up and turn it over. Cook another 20-40 seconds. Just as with the above step, you may need to sacrifice a few ladles to the stove gods to get the heat and timing just right.',
            'Carefully move crepe to a dish and cover to keep it from getting cold.',
            '(optional) If you have butter to spare: spread a thin layer over the finished crepe. This will both add flavor and help keep the crepes from sticking together when you stack them.',
            'Repeat steps 3 - 7 until you’re out of batter and looking at a nice stack of delicious crepes that need eating. Serve with sour cream, jam, maple syrup, nutella, or whatever you like your crepes with.',
        ],
        'skill_level': 'Intermediate',
        'prep_time': 10,
        'wait_time': 0,
        'cook_time': 50,
        'total_time': 60,
        'servings': 4,
    },
]
