recipes = [
    {
        'title': 'Instant Pot Plov (Rice Pilaf)',
        'description': "Plov is a hearty dish that comes in many varieties. Just about every Eastern European or Central Asian culture has a version. This one comes pretty close to what my grandma used to make so I'm gonna surmise that it's got Russian roots. While my grandma's plov took many painstaking hours to come out just right, this pressure cooker approach gets us there in half the time and none of the guesswork.",
        'ingredients': [
            {'quantity': '2 1/2 cups',
                'name': 'your favorite rice (I usually go with basmati or jasmine)', 'preparation': 'rinsed and drained'},
            {'quantity': '1 lb', 'name': 'beef chuck or beef stew meat',
                'preparation': 'cut into 3/4″ pieces'},
            {'quantity': '4 Tbsp', 'name': 'olive oil'},
            {'quantity': '4 Tbsp', 'name': 'butter'},
            {'quantity': '1', 'name': 'large onion', 'preparation': 'diced'},
            {'quantity': '3', 'name': 'large carrots',
                'preparation': 'grated'},
            {'quantity': '3 cups', 'name': 'very warm water'},
            {'quantity': '1 Tbsp', 'name': 'salt'},
            {'quantity': '1/2 tsp', 'name': 'black pepper'},
            {'quantity': '1/2 tsp', 'name': 'ground cumin'},
            {'quantity': '1/2 tsp', 'name': 'ground paprika'},
            {'quantity': '1/2 tsp', 'name': 'ground coriander'},
            {'quantity': '1', 'name': 'whole head garlic',
                'preparation': 'unpeeled, cut in half crosswise'},
            {'quantity': '1 Tbsp', 'name': 'freshly chopped parsley to garnish – optional'},
        ],
        'instructions': [
            "Rinse and drain rice and set aside. Set Instant pot to sauté and add 4 Tbsp olive oil.",
            "Once oil is hot (but not smoking), add beef in a single layer and sauté until lightly browned (usually 5 min but may take longer if you're crowding your cooking surface), stirring occasionally.",
            "Add 4 Tbsp butter and chopped onion and stir 3 minutes until softened.",
            "Add grated carrots along with seasoning mix (1 Tbsp salt, 1/2 tsp pepper, 1/2 tsp cumin, 1/2 tsp paprika, 1/2 tsp coriander) and sauté 5 minutes until softened, stirring occasionally.",
            "Spread rice evenly over the top (do not stir). Push garlic halves, cut-side-down, halfway into the rice. Pour very warm (or hot) water directly over the garlic cloves so you don't disturb the rice. Use the back of a wooden spoon to poke 5-7 holes through the rice to the bottom of the pot.",
            "Cover and cook for 30 minutes on high pressure.",
            "Give the instant pot 10 minutes to depressurize before opening the steam release valve. Open pot once it's fully depressurized",
            "Remove garlic and set aside. Stir contents to combine all ingredients.",
            "(Optional) Squeeze the garlic cloves back into the pot (they should easily slide out of the peel) if you love garlic. Stir contents again."
        ],
        'skill_level': 'Easy',
        'prep_time': 20,
        'wait_time': 0,
        'cook_time': 30,
        'total_time': 50,
        'servings': 8,
    },
    {
        'title': 'Borsh',
        'description': "Classic Ukranian beet soup. Can be made as hearty or light as you like. For reference: I use a 12qt stockpot and tend to opt for a heartier/denser version. So, if you like your soup more soupy, feel free to reduce the vegetable quantities to about 75% of what's listed below",
        'ingredients': [
            {'quantity': '2 lb', 'name': 'Beef chuck/stew meat',
                'preparation': 'cut into 1 inch cubes'},
            {'quantity': '1', 'name': 'Beef marrow bone (optional)'},
            {'quantity': '2 Tbsp', 'name': 'salt (+ more to taste)'},
            {'quantity': '3', 'name': 'large or 6 medium beets',
                'preparation': 'washed, peeled, and grated'},
            {'quantity': '4 Tbsp', 'name': 'olive oil'},
            {'quantity': '2',
                'name': 'large onions (white or yellow)', 'preparation': 'chopped'},
            {'quantity': '5', 'name': 'medium carrots', 'preparation': 'grated'},
            {'quantity': '2', 'name': 'large or 4 medium potatoes',
                'preparation': 'peeled and cut into 1 inch cubes'},
            {'quantity': '1 head', 'name': 'green cabbage',
                'preparation': 'julienned'},
            {'quantity': '2', 'name': 'tomatoes',
                'preparation': 'roughly chopped'},
            {'quantity': '3', 'name': 'bay leaves'},
            {'quantity': '1/2 tsp', 'name': 'freshly ground black pepper'},
            {'quantity': '1/3 cup', 'name': 'fresh parsley', 'preparation': 'chopped'},
            {'quantity': '3 cloves', 'name': 'garlic', 'preparation': 'pressed or minced'},
        ],
        'instructions': [
            "Cut beef into 1\" cubes and place in a large stockpot (add marrow bone if using). Fill halfway with cold water. Add bayleaves and 2 Tbsp salt and set over a high flame. ('Note': If at any point it looks like you have too much water, just let some boil off before adding extra ingredients. I also keep a kettle of boiled water on the side just in case it looks like I don't have enough.)",
            "As the water comes to boil, periodically remove the foam crud as soon as surfaces. This is purely for aesthetics. The gunk is just broken down proteins. It's not bad for you, but it makes for a cloudy soup.",
            "Once the water is boiling, reduce heat, partially cover, and simmer 45 minutes to an hour.",
            "Grate beets on the large grater holes (or use a food processor. I bought mine a few winters ago after making borsh three weeks in a row and not being able to look at my grater anymore). Place grated in a large saute pan or heavy-bottom skillet with 4 Tbsp olive oil and 1 Tbsp vinegar and saute for 5-10 minutes on medium heat. Then, reduce heat to med/low and add chopped tomatoes. Mix thoroughly and saute until starting to soften, stirring as needed (about 10-15 min). Remove from pan and set aside.",
            "In the same skillet (no need to wash it), saute chopped onion in 1 Tbsp butter for 5 minutes. Add grated carrot and sautee another 5 min or until softened, adding more oil and/or lower heat if you think it may start to burn.",
            "Once the meat has been cooking at least 45 min, add julienned cabbage",
            "Once the cabbage has softened (about 10 minutes), add cubed potatoes, onions, and carrots.",
            "Wait 10 minutes, then add the beets.",
            "After 10 minutes of simmering everything together, remove the pot from heat, add chopped parsley and pressed garlic, stir and cover. Let rest for 20 minutes for the flavors to diffuse.",
            "*serve with a dollop of sour cream (technically optional but absolutely essential in my home)",
        ],
        'skill_level': 'Medium',
        'prep_time': 30,
        'wait_time': 0,
        'cook_time': 90,
        'total_time': 120,
        'servings': 8,
    },
    {
        'title': 'Goulash Stew',
        'description': "Some of the best goulash I've ever had was at Cafe Katja, a little Austrian place on Orchard Street in New York. Traditional Hungarian Goulash is a light beef soup. Cafe Katja made theirs in to a thick, melt-in-your-mouth stew. This recipe  pretty close to Katja's goulash.",
        'ingredients': [
            {'quantity': '4 tbsp', 'name': 'olive oil'},
            {'quantity': '2 1/2 lbs', 'name': 'lean stewing beef',
                'preparation': 'cut into 1 inch pieces'},
            {'quantity': '1 tsp', 'name': 'salt or to taste'},
            {'quantity': '1 tsp', 'name': 'pepper or to taste'},
            {'quantity': '2', 'name': 'large onions',
                'preparation': 'roughly chopped'},
            {'quantity': '5 cloves', 'name': 'garlic', 'preparation': 'minced'},
            {'quantity': '3 tbsp', 'name': 'sweet paprika'},
            {'quantity': '1 tsp', 'name': 'caraway seeds', 'preparation': 'ground'},
            {'quantity': '1 tsp', 'name': 'dried oregano'},
            {'quantity': '3', 'name': 'bay leaves'},
            {'quantity': '1 tsp', 'name': 'brown sugar'},
            {'quantity': '1/2 cup', 'name': 'tomato sauce OR 2 tomatoes'},
            {'quantity': '2 tbsp', 'name': 'balsamic vinegar'},
            {'quantity': '4 cups', 'name': 'beef broth (I use half a bullion cube and water)'},
            {'quantity': '2 tbsp', 'name': 'parsley',
                'preparation': 'chopped, for garnish'},
        ],
        'instructions': [
            "Heat a large deep skillet or Dutch oven over medium-high heat then add olive oil (You can also use an instant pot)",
            "When the oil is hot add beef. Season generously with salt and pepper and sear the beef until it starts to brown (usually 5 min but may take longer if you have a crowded cooking surface).",
            "Add onions and garlic and cook until the onions soften and become translucent (5-10 minutes). Reduce heat to medium.",
            "Add paprika, caraway seeds, oregano, bay leaves and brown sugar. Stir everything together and cook for 30 seconds.",
            "Add the tomato sauce (or tomatoes), balsamic vinegar, beef broth (or bullion) and stir (if using instant pot, add only 2 cups broth)",
            "Bring to a boil, then cover and cook on low for about 2 hours or until the beef is fork tender, stirring occasionally. The liquid will reduce down a lot as the beef cooks, so feel free to add more water as needed.",
            "If using instant pot, once the pot comes to boil, cover and seal pot, and cook on high pressure for 35 minutes. Once done, let the pot depressurize on its own for 15-20 minutes before releasing pressure.",
            "(Optional) At this point, you'll have some soupy goulash. From here, I like to return it to heat and simmer down until it's reduced to desired viscocity."
            "Taste for seasoning and adjust with salt and pepper if needed.",
            "Garnish with chopped parsley and serve over noodles or mashed potatoes.",
        ],
        'skill_level': 'Medium',
        'prep_time': 10,
        'wait_time': 0,
        'cook_time': 180,
        'total_time': 190,
        'servings': 8,
    },
    {
        'title': 'Linguine with White Clam Sauce',
        'description': "There are a lot of ways to prepare linguine with clam sauce, but I've repeatedly gone back to this one because it's one of the simpler approaches and yields delicious results. This recipe uses canned clams, which keeps it low maintenance. All the necessary ingredients can hang out in your kitchen cabinet for months, while fresh clams need to be used within a few days.",
        'ingredients': [
            {'quantity': '1 pound', 'name': 'linguini'},
            {'quantity': '1 tsp', 'name': 'salt'},
            {'quantity': '1/4 cup', 'name': 'extra-virgin olive oil'},
            {'quantity': '8 fillets', 'name': 'flat anchovies'},
            {'quantity': '4 cloves', 'name': 'garlic', 'preparation': 'chopped'},
            {'quantity': '1 teaspoon', 'name': 'dried thyme leaves'},
            {'quantity': '1/2 tsp', 'name': 'crushed red pepper flakes'},
            {'quantity': '1/2 cup', 'name': 'dry white wine'},
            {'quantity': '2 (15-ounce) cans',
             'name': "whole or chopped baby clams with their juice (minced will do in a pinch; you'll still get all the flavor but the clam texture will be lost)"},
            {'quantity': '1 handful', 'name': 'flat-leaf parsley',
                'preparation': 'chopped'},
        ],
        'instructions': [
            "Bring a large pot of water to a boil. You should use just enough water to ensure your pasta will be fully submerged for the 11-14 minutes it will take to cook. ",
            "Add salt and the linguini and cook to an extra chewy al dente. The linguini will cook more in sauce. (I know the ingredients say 1tsp salt, but I always cook pasta the same way: salt the water until it tastes like the sea.)",
            "While the pasta is cooking, prepare the sauce: place a large skillet or sautee pan over medium heat and add oil, anchovies, garlic, thyme, and red pepper flakes.",
            "Cook together until anchovies melt into oil and disintegrate completely. Be careful not to burn the garlic; stir frequently and reduce heat if needed.",
            "Add wine, clams, and clam juice to the pan, turn heat to high, and give the pan a shake: jostle back and forth for about 3-5 minutes (you should see a mist evaporating off the sauce). Don't leave pan unattended or still for this part as the garlic will burn if left sitting on high heat (learned that the hard way by ruining a batch of sauce at the very end). Reduce to a low simmer.",
            "(Optional) you could buy a separate bottle of clam juice to add more briney flavor to your sauce.",
            "When pasta is ready, use tongs to transfer directly from the pot into the sauce. The starchy water will help the sauce coat the pasta.",
            "Toss the pasta in sauce until well mixed, cover, and let sit for 5 minutes to allow the flavor to absorb.",
            "Remove from heat, add parsley, and serve.",
        ],
        'skill_level': 'Easy',
        'prep_time': 10,
        'wait_time': 0,
        'cook_time': 25,
        'total_time': 35,
        'servings': 4,
    },
    {
        'title': 'Blueberry Buttermilk Pancakes',
        'description': "These are fantastic with or without berries. Also work with other fruits.",
        'ingredients': [
            {'quantity': '2 cups', 'name': 'all-purpose flour'},
            {'quantity': '1/4 cup', 'name': 'sugar'},
            {'quantity': '2 1/4 teaspoons', 'name': 'baking powder'},
            {'quantity': '1/2 teaspoon', 'name': 'baking soda'},
            {'quantity': '1/2 teaspoon', 'name': 'salt'},
            {'quantity': '4', 'name': 'eggs'},
            {'quantity': '2 cups', 'name': 'buttermilk'},
            {'quantity': '2 tbsp', 'name': 'unsalted butter, plus more for frying'},
            {'quantity': '1 cup', 'name': 'blueberries',
                'preparation': 'fresh or frozen'},
        ],
        'instructions': [
            "I like to set up for this by laying out three mixing bowls to work in. One of them should be large enough to hold all the ingredients (not including any fruits or berries you're using). I have three nested bowls which are pretty perfect for this.",
            "Prepare your dry mix in the large bowl: Sift together the flour, baking powder, baking soda, and salt (NO sugar here yet). (Note: You can do this in advance and stick it in the freezer. When using mix from the freezer, resift the contents before combining with wet ingredients.)",
            "Separate egg whites and yolks between the other two bowls: whites in the larger bowl, yolks in the smaller.",
            "Melt 2tbsp (1/4 cup) butter and set aside. Use low heat so your butter doesn't burn.",
            "Add sugar to egg yolks and whisk together (immersion blender also works for this and the next step)",
            "Whisk the egg whites until they're foamy, then combine with buttermilk.",
            "(Optional) once your butter has cooled down, pour it into the egg yolk/sugar mixture while whisking. (Pouring hot butter onto the yolks will cook them).",
            "Pour the yolk/sugar/butter mixture into the whites/buttermilk mixture while whisking. (If you didn't want your butter to cool down, you can pour it in here last, since the buttermilk will cool it down quickly enough not to cook the eggs).",
            "Once the wet mix is ready, pour it over the dry, and mix into a lumpy batter. Be careful not to over mix, or you'll get less than fluffy pancakes. For reference: your mix should not be smooth and uniform; you should still see clumps of flour in it.",
            "Heat some butter in a skillet over low-medium heat (any skillet will do, but nonstick will save you a headache here). Use a large soup spoon to scoop a heaping spoonful of batter onto the skillet. Sprinkle the top with some of the blueberries. Cook for 2 to 3 minutes on each side. You'll probably need to calibrate here to get the right temperature and cooking time combinations (the first batch or two can be considered test-rounds because of this.)",
            "Serve with a dollop of whipped cream and maple syrup.",
        ],
        'skill_level': 'Easy',
        'prep_time': 20,
        'wait_time': 0,
        'cook_time': 15,
        'total_time': 25,
        'servings': 4,
    },
    {
        'title': 'Pan Roasted Chicken Thighs',
        'description': '',
        'ingredients': [
            {'quantity': "8", 'name': "skin-on, bone-in chicken thighs"},
            {'quantity': "", 'name': "Kosher salt and freshly ground black pepper"},
            {'quantity': "1 tablespoon", 'name': "vegetable oil"},
        ],
        'instructions': [
            "Preheat oven to 475°F.",
            "Season chicken with salt and pepper.",
            "Heat oil in a 12\" cast-iron or heavy nonstick skillet over high heat until hot but not smoking.",
            "Nestle chicken in skillet, skin side down, and cook 2 minutes",
            "Reduce heat to medium-high; continue cooking skin side down, occasionally rearranging chicken thighs and rotating pan to evenly distribute heat, until fat renders and skin is golden brown, about 12 minutes",
            "Transfer skillet to oven and cook 13 more minutes.",
            "Flip chicken; continue cooking until skin crisps and meat is cooked through, about 5 minutes longer.",
            "Transfer to a plate; let rest 5 minutes before serving.",
        ],
        'skill_level': 'Easy',
        'prep_time': 5,
        'wait_time': 0,
        'cook_time': 30,
        'total_time': 35,
        'servings': 4,
    },
    {
        'title': 'Wild Rice Salad',
        'description': 'Hearty and filling',
        'ingredients': [
            {'quantity': "2 cups", 'name': "water"},
            {'quantity': "1/2 teaspoon", 'name': "salt"},
            {'quantity': "1 cup", 'name': "wild rice"},
            {'quantity': "1 (6-ounce) jar", 'name': "marinated artichoke hearts",
             'preparation': "drained and halved, reserve marinade"},
            {'quantity': "1 (6-ounce) can", 'name': "green peas", 'preparation': "drained"},
            {'quantity': "1/3 cup", 'name': "green bell pepper",
                'preparation': "coarsly chopped"},
            {'quantity': "3", 'name': "green onions",
                'preparation': "chopped, white and green parts"},
            {'quantity': "1 cup", 'name': "cherry or grape tomatoes",
                'preparation': "halved"},
            {'quantity': "1/2 cups", 'name': "olive oil"},
            {'quantity': "1/2 cup", 'name': "white vinegar"},
            {'quantity': "1/4 cup", 'name': "Parmesan", 'preparation': "grated"},
            {'quantity': "1 tsp", 'name': "sugar"},
            {'quantity': "1 tsp", 'name': "salt"},
            {'quantity': "1/4 tsp", 'name': "paprika"},
            {'quantity': "1 clove", 'name': "garlic", 'preparation': "minced"},
        ],
        'instructions': [
            "In a 1-quart pot with a lid, bring 2 cups water and the salt to a boil. Add the rice and stir well. Reduce the heat to low, cover, and simmer for 45 minutes to 1 hour. Drain excess liquid from the rice.",
            "Meanwhile, combine all the dressing ingredients in a jar with a tight-fitting lid and shake well. Refrigerate until ready to use.",
            "In a large bowl, combine the rice, artichoke hearts, peas, green pepper, green onions, tomatoes, reserved marinade, and half of the dressing. Toss well. Cover and chill or eat at room temperature. Just before serving, toss again and taste. Add some of the remaining dressing, if desired. Sprinkle with the almonds and serve."
        ],
        'skill_level': 'Easy',
        'prep_time': 15,
        'wait_time': 0,
        'cook_time': 45,
        'total_time': 60,
        'servings': 8,
    },
]
