# Generated by Django 3.0.4 on 2020-03-31 21:49

from django.db import migrations
from ..seed_data.recipe_data import recipes as recipe_data


def seed_recipes(apps, schema_editor):
    Recipe = apps.get_model('recipes', 'Recipe')
    Ingredient = apps.get_model('recipes', 'Ingredient')
    Instruction = apps.get_model('recipes', 'Instruction')
    User = apps.get_model('recipes', 'User')

    user = User.objects.create(
        username='Mike',
        email='mikefeldberg@protonmail.com',
        password='password',
    )

    new_ingredients = []
    new_instructions = []

    for recipe in recipe_data:
        ingredients = recipe.pop('ingredients')
        instructions = recipe.pop('instructions')
        new_recipe = Recipe(
            user_id=user.id,
            **recipe,
        )

        new_recipe.save()

        for ingredient in ingredients:
            new_ingredients.append(Ingredient(
                recipe_id=new_recipe.id,
                **ingredient,
            ))

        for idx, instruction in enumerate(instructions):
            new_instructions.append(Instruction(
                recipe_id=new_recipe.id,
                content=instruction,
                order=idx + 1,
            ))

    Ingredient.objects.bulk_create(new_ingredients)
    Instruction.objects.bulk_create(new_instructions)


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(seed_recipes),
    ]
