# Generated by Django 3.0.3 on 2020-02-26 22:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='posted_by',
            new_name='user',
        ),
    ]
