# Generated by Django 3.0.3 on 2020-02-27 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_auto_20200226_2244'),
    ]

    operations = [
        migrations.AddField(
            model_name='instruction',
            name='order',
            field=models.IntegerField(default=1),
        ),
    ]
