# Generated by Django 3.0.4 on 2020-03-12 20:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recipes', '0004_auto_20200311_1831'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='photo',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='title',
        ),
        migrations.AddField(
            model_name='photo',
            name='recipe',
            field=models.ForeignKey(default=5, on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='recipes.Recipe'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='photo',
            name='url',
            field=models.CharField(default=5, max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='photo',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
