# Generated by Django 3.0.4 on 2020-03-12 20:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_auto_20200312_2014'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Photo',
        ),
    ]
