# Generated by Django 3.0.4 on 2020-03-15 02:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0007_photo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='instruction',
            old_name='description',
            new_name='content',
        ),
    ]
